[package]
name = "matrix_operations_cuda"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
matrix_operations = "0.1.3"
cuda-driver-sys = "0.3.0"
